In [1]:
# CNN - convolutional layer
import numpy as np
from numpy.conftest import dtype


def convolution(image, kernel):
    i_i, i_j = image.shape
    k_i, k_j = kernel.shape
# general formula for shape of a convoluation output
    output_i = i_i - k_i + 1
    output_j = i_j - k_j + 1
    output = np.zeros((output_i, output_j))
    for i in range(output_i):
        for j in range(output_j):
# slide the kernel through image matrix. i and j controls the block size over which kermel slides. It will be same as kernel size.
            region = image[i:i + k_i, j:j + k_j]
#            print(region)
            output[i, j] = np.sum(region*kernel)
    return output

image = np.array([
    [1, 2, 3, 0, 1],
    [4, 5, 6, 1, 2],
    [7, 8, 9, 2, 3],
    [1, 2, 3, 0, 1],
    [4, 5, 6, 1, 2]
])

kernel = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

output = convolution(image, kernel)
print(output)

[[  6. -12. -12.]
 [  6. -12. -12.]
 [  6. -12. -12.]]


In [2]:
arr = ['a','c','n','m']
for i in range(len(arr)):
    if arr[i] == 'm':
        print('found')


found
