## Tensor Slicing

In [9]:
import torch

In [13]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

In [14]:
# Access a single element ([row,column])
print(tensor[0,1])

tensor(2)


In [20]:
# Slice the second row ([row,:])
print(tensor[1,:])

tensor([4, 5, 6])


In [23]:
# Slice the second column ([:,column])
print(tensor[:,1])

tensor([2, 5, 8])


In [26]:
# To keep the output as a column vector, use slicing with ranges, e.g., x[:, 2:3] yields a (m,1) column vector
print(tensor[:,2:3])

tensor([[3],
        [6],
        [9]])


In [ ]:
# To keep the output as a row vector, use slicing with ranges, e.g., x[:, 2:3] yields a (m,1) column vector
print(tensor[:,2:3])

In [29]:
tensor2 = torch.tensor([[1, 2, 3,1],[4, 5, 6,1],[7, 8, 9,1],[10, 11, 12,1]])

In [30]:
print(tensor2)

tensor([[ 1,  2,  3,  1],
        [ 4,  5,  6,  1],
        [ 7,  8,  9,  1],
        [10, 11, 12,  1]])


In [31]:
print(tensor2.shape)

torch.Size([4, 4])


In [32]:
print(tensor2.ndim)

2


In [34]:
print(tensor2[:,2:3])

tensor([[ 3],
        [ 6],
        [ 9],
        [12]])


In [35]:
print(tensor2[2:,:])

tensor([[ 7,  8,  9,  1],
        [10, 11, 12,  1]])


In [42]:
#Extending slicing to n dimension(dim) - dim_0:,dim_1:,dim_2 :,...din_n
# Each dim has format row:,col:,step default step is 1
# Example :,2:3:2,:



tensor([], size=(4, 0), dtype=torch.int64)
