## This notebook demonstrate the python system level commands/programming

### 1. File I/O and Directory Management

In [2]:
import os

DATA_DIR = 'data'
if not os.path.exists(DATA_DIR):
    os.mkdir(DATA_DIR)
    print('Directory ', DATA_DIR, ' Created ')
else:
    print('Directory ', DATA_DIR, ' already exists')


Directory  data  already exists


### how setting a seed ensures reproducibility, especially when initializing weights.

In [15]:
import numpy as np
import random
import torch

# Example: Create a matrix with a specific shape and type
seed_matrix_zeros = torch.zeros(2, 4)
print("\nSeed Matrix (Zeros):")
print(seed_matrix_zeros)


Seed Matrix (Zeros):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [18]:
# Example: Create a 3x3 matrix with random values from a normal distribution (mean=0, std=1)
seed_matrix_normal = torch.randn(3, 3)
print("\nSeed Matrix (Normal):")
print(seed_matrix_normal)


Seed Matrix (Normal):
tensor([[ 1.3525,  0.6863, -0.3278],
        [ 0.7950,  0.2815,  0.0562],
        [ 0.5227, -0.2384, -0.0499]])


In [20]:
# 2. Create a matrix (tensor)
# Example: Create a 3x3 matrix with random values from a uniform distribution [0, 1)
seed_matrix_uniform = torch.rand(3, 3)
print("Seed Matrix (Uniform):")
print(seed_matrix_uniform)

Seed Matrix (Uniform):
tensor([[0.2018, 0.9497, 0.6666],
        [0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025]])


* torch.manual_seed(seed): Sets the seed for PyTorch's CPU random number generator.
* torch.cuda.manual_seed(seed) and torch.cuda.manual_seed_all(seed): Used to set the seed for the GPU if you are using CUDA
* torch.rand(shape): Creates a tensor filled with random numbers from a uniform distribution over [0,1]
* torch.randn(shape): Creates a tensor filled with random numbers from a standard normal distribution.
* Reproducibility: By setting a seed, you ensure that your experiments are reproducible, meaning you can get the exact same results if you re-run the code.



In [29]:
# Set the random seed
np.random.seed(0)

# Generate a reproducible 2x2 random matrix
matrix = np.random.rand(2, 2)

print(matrix)

## without np.random.seed(0) - np.random.rand(2,2) will produce matrix with differnt randome numbers everytime it is run


[[0.5488135  0.71518937]
 [0.60276338 0.54488318]]
